name: Generate Snake Animation

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Also run on every push on the main/master branch
  push:
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needs write permission to push the generated files
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate the snake animation
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=blue
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Commit and push the generated files
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "feat: Generate new snake animation"
            git push
          fi
